### ISSUE TITLE
感谢并提个建议

### ISSUE THREAD

**Issue by rsun-thoughtworks** [bkdwei/kd163PhotoDownloader#1]
楼主的这个很好，感谢下。

另外，我们不会用，是否可以增加一个一步一步的说明，指导我们运行。

**Comment by bkdwei** [comment]
好，我晚上下班回去写个详细的使用说明。

**Comment by bkdwei** [comment]
> 
> 
> 楼主的这个很好，感谢下。
> 
> 另外，我们不会用，是否可以增加一个一步一步的说明，指导我们运行。

安装步骤和使用说明已经写好了，请查看README.md
