### ISSUE TITLE
赞一个！以及编码问题（虽然今天之后也就用不上了）

### ISSUE THREAD

**Issue by wyfsh** [bkdwei/kd163PhotoDownloader#2]
大赞一个！非常有用！
另外运行中有时会遇到相册名解析编码报错（可能是某些漫画里的日文字符），尝试将album.py中第150和223行中的`gb2312`更换为`gbk`，可以解决该问题。

**Comment by bkdwei** [comment]
非常感谢你的使用，哈哈哈
